"""empty message

Revision ID: 49455ae0816a
Revises: 411cc0fc2991
Create Date: 2023-03-10 21:00:10.733518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49455ae0816a'
down_revision = '411cc0fc2991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poke_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('poke_count')

    # ### end Alembic commands ###
